# Generated by Django 4.2.1 on 2023-07-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateTimeField(verbose_name='logdate')),
                ('name', models.CharField(max_length=200)),
                ('steamid', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
            ],
        ),
    ]
