# Generated by Django 4.2.3 on 2023-08-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lC', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log_date',
            field=models.DateField(verbose_name='logdate'),
        ),
    ]
