# Generated by Django 4.2.3 on 2023-08-06 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lC', '0002_alter_log_log_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='logtime'),
            preserve_default=False,
        ),
    ]
