# Generated by Django 4.2.3 on 2023-08-30 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lC', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
